### ISSUE TITLE
请问这个项目还在维护吗？我遇到了问题，不知道如何解决

### ISSUE THREAD

**Issue by lgyjg** [wahyd4/Libr#6]
我在安装了相关的依赖后，运行```rails s```，应用提示"PG::ConnectionBad", 错误堆栈如下：

``` shell
PG::ConnectionBad (fe_sendauth: no password supplied
):
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `initialize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `new'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `connect'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
  /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
  /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_handling.rb:87:in `connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/query_cache.rb:43:in `rescue in call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/query_cache.rb:32:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:82:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/reloader.rb:73:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.0/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/static.rb:64:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/deflater.rb:25:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `catch'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/connection.rb:53:in `process'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/connection.rb:39:in `receive_data'
  vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
  vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/backends/base.rb:73:in `start'
  vendor/bundle/ruby/2.3.0/gems/thin-1.6.2/lib/thin/server.rb:162:in `start'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
  vendor/bundle/ruby/2.3.0/gems/rack-1.5.2/lib/rack/server.rb:264:in `start'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/server.rb:69:in `start'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:81:in `block in server'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `tap'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `server'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  vendor/bundle/ruby/2.3.0/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
```
从ｌｏｇ分析应该是没有配置密码，但是我没有找到配置密码的地方，能够指导下，谢谢

**Comment by wahyd4** [comment]
没有在维护了，不过你可以先把问题的细节描述清楚。
yangjg <notifications@github.com>于2017年2月15日 周三下午8:41写道：

**Comment by lgyjg** [comment]
在安装过程中，对一些依赖进行了升级．具体改动如下：
```git
diff --git a/Gemfile b/Gemfile
index 5b36e23..1d90d68 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,7 +2,7 @@ source 'https://rubygems.org'
 
 # source 'http://ruby.taobao.org'
 
-ruby '2.1.0'
+ruby '2.3.1'
 
 gem 'rails', '4.1.0'
 
diff --git a/Gemfile.lock b/Gemfile.lock
index ebf4296..9355745 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -123,7 +123,7 @@ GEM
     diff-lcs (1.2.5)
     docile (1.1.4)
     erubis (2.7.0)
-    eventmachine (1.0.3)
+    eventmachine (1.0.4)
     execjs (2.2.0)
     faraday (0.9.0)
       multipart-post (>= 1.2, < 3)
@@ -163,7 +163,7 @@ GEM
       thor (>= 0.14, < 2.0)
     jquery-ui-rails (4.2.1)
       railties (>= 3.2.16)
-    json (1.8.1)
+    json (1.8.3)
     jwt (1.0.0)
     kaminari (0.16.1)
       actionpack (>= 3.0.0)
@@ -194,7 +194,7 @@ GEM
       multi_xml (~> 0.5)
       rack (~> 1.2)
     orm_adapter (0.5.0)
-    pg (0.17.1)
+    pg (0.19.0)
     polyamorous (1.0.0)
       activerecord (>= 3.0)
     polyglot (0.3.5)
@@ -375,3 +375,9 @@ DEPENDENCIES
   thin
   unicorn
   will_paginate
+
+RUBY VERSION
+   ruby 2.3.1p112
+
+BUNDLED WITH
+   1.13.7

```

**Comment by wahyd4** [comment]
这个错是说你的postgres 数据库没有设置正确哦，database.yml 里面的密码和数据库真实密码不匹配。和升级gem 没有关系。
yangjg <notifications@github.com>于2017年2月15日 周三下午8:47写道：

**Comment by lgyjg** [comment]
感谢能抽空回复我．多谢．确实是没有配置数据库．顺便问一句，这个项目的域名下的站点似乎访问不了了．这个项目挺好的呀，为什么不维护了，是有更好的替代软件了吗？

**Comment by wahyd4** [comment]
之所以没有维护，是因为没有人使用它。如果你要访问可以使用libr.herokuapp.com ，到时候可能会弹出提示框，关闭忽略就是了。
yangjg <notifications@github.com>于2017年2月15日 周三下午8:53写道：

**Comment by lgyjg** [comment]
谢谢大神．我好好学习下．

**Comment by lgyjg** [comment]
我的数据库配置如下：
```yml
test:
  adapter: postgresql
  encoding: unicode
  database: libr_test
  pool: 5
  user: postgres
  password: postgres123
  host: 127.0.0.1:5432

production:
  adapter: postgresql
  encoding: unicode
  database: libr_production
  pool: 20
  host: 127.0.0.1:5432
  user: postgres
  password: postgres123
```
本地通过控制台可以访问相关的数据库：
```shell
ts@ts-OptiPlex-3020:~/githubPro/Libr/config$ psql -U postgres -d libr_test -h 127.0.0.1 -p 5432
Password for user postgres: 
psql (9.5.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

libr_test=# \l
                                     List of databases
      Name       |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------------+----------+----------+-------------+-------------+-----------------------
 libr_production | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | 
 libr_test       | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | 
 postgres        | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | 
 template0       | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | =c/postgres          +
                 |          |          |             |             | postgres=CTc/postgres
 template1       | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | =c/postgres          +
                 |          |          |             |             | postgres=CTc/postgres
(5 rows)

libr_test=# 
```
但是仍旧会报出以上的异常堆栈，能否帮忙看下．谢谢

**Comment by wahyd4** [comment]
Rails s 用的是development 环境，这些都是rails 基础知识。你自己多看文档吧。
yangjg <notifications@github.com>于2017年2月15日 周三下午9:33写道：

**Comment by lgyjg** [comment]
没接触过Rails，还请见谅，多谢，那我再自己研究下，主要是想先快速搭起来看看效果。

**Comment by lgyjg** [comment]
该问题已经解决：
1. 创建数据库：```sudo -u postgres createdb -O postgres libr_development```
2. 修改数据库配置文件：
``` yml
development:
  adapter: postgresql
  encoding: unicode
  database: libr_development
  pool: 5
  user: postgres
  password: postgres123
  host: localhost
```

此时能够访问网站，但是图书列表、登录、注册等功能异常，可能需要创建相应的表单，并导入数据才能够正常。

**Comment by lgyjg** [comment]
多问一句，请问这个应用相关数据库的创建需要单独创建吗？还是在运行时会直接创建，或者有没有运行的脚本？

**Comment by wahyd4** [comment]
最基本的rails 知识，看文档吧。rails 里面不需要手动建表，建库
yangjg <notifications@github.com>于2017年2月15日 周三下午10:46写道：

**Comment by lgyjg** [comment]
[捂脸] 那数据库配置正确了还需要做什么呢？还是会报好几个错误。真心懵了。

图书列表报错：
```
Showing /home/ts/githubPro/Libr/app/views/book/index.html.slim where line #10 raised:
PG::UndefinedTable: ERROR:  relation "books" does not exist
LINE 1: SELECT  "books".* FROM "books"   ORDER BY id DESC LIMIT 24 O...
                               ^
: SELECT  "books".* FROM "books"   ORDER BY id DESC LIMIT 24 OFFSET 0
Extracted source (around line #10):
 div.clearfix
   div.row-fluid
     div
       - @books.each do |book|
         div.one-item
           div
             a href="/books/#{book.id}"
Rails.root: /home/ts/githubPro/Libr
Application Trace | Framework Trace | Full Trace
app/views/book/index.html.slim:10:in `_app_views_book_index_html_slim__3372790932477631354_44659540'
app/controllers/book_controller.rb:49:in `list'
```
登录和注册报错：
``` 
PG::UndefinedTable: ERROR: relation "users" does not exist LINE 5: WHERE a.attrelid = '"users"'::regclass ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"users"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum
```
这些错误都和数据库相关，我还没有在代码中找到相关创建表的代码，明天再调查吧。

**Comment by wahyd4** [comment]
http://guides.rubyonrails.org/command_line.html

**Comment by lgyjg** [comment]
经过了一晚上的时间终于调通了。真心不少坑啊。

如果在readme中这样写不就好多了。

1. 下载代码
```shell
git clone git@github.com:wahyd4/Libr.git
```
2. 下载安装postgres数据库
``` shell
sudo apt-get update
sudo apt-get install postgresql postgresql-contrib
```

3. 安装依赖
```
cd Libr
bundle install
```

4. 创建数据库
```shell
bundle exec rake db:create
```

5. 创建数据表
```shell
bundle exec rake db:migrate
```
6. 运行应用
```shell
rails server
```

最后感谢作者的辛勤劳动。
